version: "3.9"

services:
  app:
    image: bridicarlos/goodfood:1.3
    hostname: goodfood
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db-postgres:5432/food
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres    
    ports:
      - "8080:8080"    
    depends_on:
      - db-postgres
  db-postgres:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=food
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/create_database.sql
networks:
  app-network:
