version: "3.9"

services:
  app:
    image: bridicarlos/goodfood:latest
    hostname: goodfood
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db-postgres:5432/food
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres    
    ports:
      - "8080:8080"    
    depends_on:
      - db-postgres
      - db-redis
  db-postgres:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=food
    ports:
      - "5432:5432"
  db-redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
networks:
  app-network:
