springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/food}
  application:
    name: Good Food Service
  jpa:
    hibernate:
      ddl-auto: update
  flwyay:
    validateMigrationNaming: false
    locations: classpath:db/migration
    

food:
  integration:
    product:
      name: goodfood-product 
      url: localhost:8081
    
server:
  port: 8080
