apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodfood
  labels:
    app: goodfood-postech
spec:
  selector:
    matchLabels:
      app: goodfood-postech
  template:
    metadata:
      labels:
        app: goodfood-postech
    spec:
      containers:
      - name: goodfood-postech
        image: bridicarlos/goodfood:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m" 
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_URL
        - name: SERVER_PORT
          value: "8080"
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: REDIS_HOST
        - name: REDIS_PORT
          value: "6379"