apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodfood
  labels:
    app: goodfood-postech
spec:
  selector:
    matchLabels:
      app: goodfood-postech
  template:
    metadata:
      labels:
        app: goodfood-postech
    spec:
      containers:
      - name: goodfood-postech
        image: bridicarlos/goodfood:1.9.2
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m" 
        env:
        - name: DATABASE_URL
          value: jdbc:postgresql://postgresql-db:5432/food
        - name: SERVER_PORT
          value: "8080"
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres